package com.example.spring_boot_project_api.service.impl;

import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.security.MessageDigest;
import java.util.Base64;
import java.util.HexFormat;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.example.spring_boot_project_api.config.JwtTokenProvider;
import com.example.spring_boot_project_api.config.TelegramBotProperties;
import com.example.spring_boot_project_api.dto.request.auth.TelegramLoginRequest;
import com.example.spring_boot_project_api.dto.response.auth.AuthResponse;
import com.example.spring_boot_project_api.enums.Role;
import com.example.spring_boot_project_api.exception.BadRequestException;
import com.example.spring_boot_project_api.exception.UnauthorizedException;
import com.example.spring_boot_project_api.mapper.UserMapper;
import com.example.spring_boot_project_api.model.User;
import com.example.spring_boot_project_api.repository.UserRepository;
import com.example.spring_boot_project_api.service.TelegramAuthService;

@Service
public class TelegramAuthServiceImpl implements TelegramAuthService {

    private static final String HMAC_ALGORITHM = "HmacSHA256";
    private static final long MAX_AUTH_AGE_SECONDS = 24 * 60 * 60L;
    private static final String EMAIL_DOMAIN = "blossom.local";
    private static final String SYNT_EMAIL_PREFIX = "tg_";

    private final TelegramBotProperties properties;
    private final UserRepository userRepository;
    private final JwtTokenProvider tokenProvider;
    private final PasswordEncoder passwordEncoder;

    public TelegramAuthServiceImpl(TelegramBotProperties properties,
                                   UserRepository userRepository,
                                   JwtTokenProvider tokenProvider,
                                   PasswordEncoder passwordEncoder) {
        this.properties = properties;
        this.userRepository = userRepository;
        this.tokenProvider = tokenProvider;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    @Transactional
    public AuthResponse telegramLogin(TelegramLoginRequest request) {
        if (!isEnabled()) {
            throw new BadRequestException(
                    "Telegram sign-in is not configured on this server");
        }

        validateSignature(request);

        User user = userRepository.findByTelegramId(request.id())
                .map(existing -> {
                    if (Boolean.TRUE.equals(existing.getIsDeleted())) {
                        throw new UnauthorizedException("Account has been deleted");
                    }
                    updateTelegramProfile(existing, request);
                    return existing;
                })
                .orElseGet(() -> createUser(request));

        String token = tokenProvider.generateToken(user);
        return AuthResponse.of(
                token, tokenProvider.getExpirationMs(),
                UserMapper.toUserResponse(user));
    }

    @Override
    public boolean isEnabled() {
        return properties.hasToken() && properties.getUsername() != null
                && !properties.getUsername().isBlank();
    }

    @Override
    public String botUsername() {
        return properties.getUsername();
    }

    private void validateSignature(TelegramLoginRequest request) {
        long nowSeconds = System.currentTimeMillis() / 1000L;
        long authDate = request.authDate() == null ? 0L : request.authDate();

        if (nowSeconds - authDate > MAX_AUTH_AGE_SECONDS || authDate > nowSeconds + 5 * 60L) {
            throw new UnauthorizedException("Telegram login data has expired or is from the future");
        }

        if (!properties.hasToken() || request.hash() == null || request.hash().isBlank()) {
            throw new UnauthorizedException("Invalid Telegram login hash");
        }

        String dataCheckString = "auth_date=" + authDate
                + "\nuser_id=" + request.id();
        String expectedHash = hmacSha256Hex(dataCheckString, properties.getToken());

        if (!MessageDigest.isEqual(
                request.hash().trim().getBytes(StandardCharsets.UTF_8),
                expectedHash.getBytes(StandardCharsets.UTF_8))) {
            throw new UnauthorizedException("Invalid Telegram login hash");
        }
    }

    private User createUser(TelegramLoginRequest request) {
        User user = new User();
        user.setName(displayName(request));
        user.setEmail(syntheticEmail(request.id()));
        user.setPassword(autogeneratedPassword());
        user.setRole(Role.CUSTOMER);
        user.setIsActive(true);
        user.setTelegramId(request.id());
        user.setTelegramPhotoUrl(request.photoUrl());
        return userRepository.save(user);
    }

    private void updateTelegramProfile(User user, TelegramLoginRequest request) {
        boolean changed = false;
        if (request.username() != null && !request.username().isBlank()) {
            user.setName(request.username().trim());
            changed = true;
        } else if (request.firstName() != null && !request.firstName().isBlank()) {
            user.setName(displayName(request));
            changed = true;
        }
        if (request.photoUrl() != null && !request.photoUrl().isBlank()
                && !request.photoUrl().equals(user.getTelegramPhotoUrl())) {
            user.setTelegramPhotoUrl(request.photoUrl());
            changed = true;
        }
        if (changed) {
            userRepository.save(user);
        }
    }

    private String displayName(TelegramLoginRequest request) {
        if (request.username() != null && !request.username().isBlank()) {
            return request.username().trim();
        }
        return request.firstName().trim()
                + (request.lastName() != null && !request.lastName().isBlank()
                        ? " " + request.lastName().trim()
                        : "");
    }

    private String syntheticEmail(Long telegramId) {
        return SYNT_EMAIL_PREFIX + telegramId + "@" + EMAIL_DOMAIN;
    }

    private String autogeneratedPassword() {
        byte[] bytes = new byte[32];
        new SecureRandom().nextBytes(bytes);
        return passwordEncoder.encode(
                Base64.getUrlEncoder().withoutPadding()
                        .encodeToString(bytes));
    }

    private String hmacSha256Hex(String data, String secret) {
        try {
            Mac mac = Mac.getInstance(HMAC_ALGORITHM);
            mac.init(new SecretKeySpec(
                    secret.getBytes(StandardCharsets.UTF_8), HMAC_ALGORITHM));
            return HexFormat.of().formatHex(
                    mac.doFinal(data.getBytes(StandardCharsets.UTF_8)));
        } catch (Exception ex) {
            throw new IllegalStateException(
                    "HMAC-SHA256 is not available on this JVM", ex);
        }
    }
}